### ISSUE TITLE
MEGA deleting Cryptomator files

### ISSUE THREAD

**Issue by avineas** [chenxiaolong/RSAF#73] opened 2024-10-11 10:13 UTC
When I upload Cryptomator files to Mega using RSAF, Mega automatically flags them as malware and deletes them (on desktop MEGA client it says the reason "file fingerprint missing") but using RoundSync to upload Cryptomator files to Mega works flawlessly.

For more info, see this thread: https://community.cryptomator.org/t/figured-out-how-to-access-mega-cloud-storage-on-android-via-roundsync-rclone/12921/14

**Comment by leowankerddd** [comment] 2024-10-12 03:07
Hi,

I tested RSAF with Pcloud also and the same thing happens. The files aren't necessarily being flagged as anything bad but when I upload the files from within the Cryptomator software program on Android they get uploaded, and then they disappear I can upload files with rsaf directly but not through the Cryptomator program.

It seems there is a problem with the way that rsaf and Cryptomator work together.

I'd be happy to collect debug information to assist fixing this.

When I use Roundsync, a different Rclone for Android app, it works fine.

**Comment by avineas** [comment] 2024-10-12 12:03
I also tested with pCloud, Jottacloud and Box. It's the same situation with them.

**Comment by leowankerddd** [comment] 2024-10-12 12:21
When I use rsaf to open a remote in the document UI I can successfully copy files back and forth between the phone in the cloud so there's something with the combination of rsaf and cryptometer I just don't know where to do the debugging. I'm hoping there's a way to collect debug information from rsaf I think there is. I think I did it once before using ADB but it needs a developer to give me the syntax again.

I think that what I need to do is connect my phone to my computer with ADB and then run the process of uploading a file to cryptivator using rsaf and then immediately thereafter do a dump through Android debug Bridge to my computer and then post that information to the developer and you might be able to see what's going on.

**Comment by chenxiaolong** [comment] 2024-10-12 17:11
Sorry, I don't really have any idea how to troubleshoot this.

Behavior wise, RSAF works like this rclone command:
```
rclone mount \
    --dir-cache-time 5s \
    --vfs-cache-mode writes \
    --vfs-cache-max-age 60s \
    --vfs-read-chunk-size 2M \
    --vfs-read-chunk-size-limit 8M \
    --vfs-write-back 0s
```

With the exception of copying and moving files, all requests from the client app (eg. Cryptomator) are directly passed to rclone with no additional logic. (eg. one write from the client app == one write in rclone.)

Copying/moving are the only special operations, which behave like `rclone copy`/`rclone move` instead.

---

I do not know why Round-Sync does not trigger this issue, but it does behave quite differently from RSAF. Round-Sync only supports reading and writing files from beginning to end instead of supporting random file access and it is implemented with `rclone cat` and `rclone rcat`.

---

For folks who have `adb`, you can see what exactly a client app is doing by long pressing RSAF's version number to enable debug mode and then enabling `Verbose rclone logs`. Debug mode can be disabled by long pressing the version number again.

To see the logs:

```bash
adb logcat -v color -s RcloneProvider
```

This filters the logs to only file operations and is safe to share if you don't mind the names of the accessed files being visible. **WARNING**: Do not upload a full unfiltered logcat (without `-s RcloneProvider`) when debug mode is enabled because rclone will write authentication details to the log.

This is an example of how the log looks:

```
openDocument(remote:file.txt, w, null)
ProxyFd[remote:file.txt].onGetSize()
ProxyFd[remote:file.txt].onWrite(0, 131072, <data[131072]>)
ProxyFd[remote:file.txt].onWrite(131072, 65502, <data[131072]>)
ProxyFd[remote:file.txt].onRelease()
```

In this example, a client app opened `file.txt`, wrote `131072` bytes, wrote `65502` bytes, and then closed the file.

**Comment by chenxiaolong** [comment] 2024-10-12 17:26
I was able to successfully reproduce this when creating a new Cryptomator vault. Cryptomator isn't doing anything special. It just opens a file, writes 329 bytes for the data, and then closes it:

```
openDocument(mega:CM/mega/masterkey.cryptomator.bin, w, null)
ProxyFd[mega:CM/mega/masterkey.cryptomator.bin].onGetSize()
ProxyFd[mega:CM/mega/masterkey.cryptomator.bin].onWrite(0, 329, <data[131072]>)
ProxyFd[mega:CM/mega/masterkey.cryptomator.bin].onRelease()
```

That's apparently enough to make MEGA flag the file. I have no idea what can be done about that.

**Comment by chenxiaolong** [comment] 2024-10-12 17:37
Can you please check the cloud storage from the web UI? Are the files actually missing or did RSAF just append an unexpected `.bin` extension to them?

**Comment by avineas** [comment] 2024-10-12 18:07
Yes they're in the trash with the .bin extension

**Comment by avineas** [comment] 2024-10-12 18:08
Or they were in the "SyncDebris" folder, can't remember. i uninstalled the MEGA Desktop app but i can reinstall if needed.

**Comment by chenxiaolong** [comment] 2024-10-12 20:23
I think the issue is this:

* Cryptomator creates new files with the `application/octet-stream` MIME type
* RSAF appends the `.bin` file extension corresponding to the MIME type (this is allowed--Android's SAF API does not guarantee anything about the file extension)
* Cryptomator expects there to be no file extension so it can't find the files it created
* Cryptomator deletes the `.bin` files that it doesn't expect to be there

It seems that Cryptomator assumes that all SAF providers will behave like Android's local file provider, even if that's not the documented behavior.

Please give this test build a try: https://github.com/chenxiaolong/RSAF/pull/74#issuecomment-2408689154 Since Android's local file provider has a special case for `application/octet-stream` to avoid adding a file extension, I've done the same in RSAF's provider.

**Comment by avineas** [comment] 2024-10-12 21:00
For MEGA, it works and doesnt delete the files but there's still the "file fingerprint missing" notice when using mega desktop app to sync to a local desktop folder, and the files arent synced to desktop until you open mega drive and click "solve". I guess it would be tedious to do this every time. But the files are there on the MEGA cloud, this issue is related to desktop folder sync only.

**Comment by leowankerddd** [comment] 2024-10-12 21:05
Hi,

I just upgraded to your new test build and tested it with pcloud and it can't open files that I had previously uploaded but that is to be expected all new files that I upload are there and can be downloaded as well. I will test further and also with mega. I don't use the mega desktop client i use rclone.

Before you continue try deleting all of the files that you had previously uploaded with other versions of rsaf. I'm going to delete the Vault and start with a clean Vault with this version of rsaf and report back I think that will work best.

Thank you for getting on top of this so quickly and posting a new test version that looks like it may very well solve the problem.

**Comment by chenxiaolong** [comment] 2024-10-12 21:11
Thanks for testing!

> it can't open files that I had previously uploaded

Yep, for old files, if you manually remove the `.bin` extension that RSAF previously added, it should work again.

**Comment by chenxiaolong** [comment] 2024-10-12 21:16
> For MEGA, it works and doesnt delete the files but there's still the "file fingerprint missing" notice when using mega desktop app to sync to a local desktop folder, and the files arent synced to desktop until you open mega drive and click "solve".

Any chance this could be a timing issue? Even after Cryptomator reports that a file is written/uploaded, rclone may still be in the process of uploading it in the background.

(There is unfortunately no way to get the status of these background uploads other than looking at the logs. I want to improve this, but there isn't much I can do with rclone's current design.)

**Comment by leowankerddd** [comment] 2024-10-12 22:20
Hi,

Pcloud over the brand new vault works perfectly as far as I can tell.

I uploaded a bunch of files and then I was able to tap on them and preview them prior to downloading them or sharing them which is wonderful. Denver JPEG files which is why I can preview them I guess they didn't just download but there was a download option which is nice.

I'm A Cloud Drive junkie so I will test this with some of my other Cloud drives such as Google Microsoft Mega S3 Proton Drive and perhaps SFTP just to cover the bases.

Thank again.

**Comment by chenxiaolong** [comment] 2024-10-13 02:48
I've just merged the fix in #74, which will be included in the upcoming 1.29 release. In the meantime, feel free to continue using the test build.

**Closed** 2024-10-13 02:47 UTC

**Comment by leowankerddd** [comment] 2024-10-13 02:55
> I've just merged the fix in #74, which will be included in the upcoming 1.29 release. In the meantime, feel free to continue using the test build.

THANK YOU!

This is huge because it enables those who use cryptomator to use any one of the cloud providers supported by rclone via your software.

I've already put a link to RSAF in the cryptomator knowledge base. I will update it to include that people can start using it beginning with the next release 1.29.

**Comment by avineas** [comment] 2024-10-13 11:53
Thank you for the quick fix, you're a legend. Regarding the MEGA desktop client, do you plan on fixing the issue or not? Just so i know should i migrate to another drive or wait for the fix.

**Comment by chenxiaolong** [comment] 2024-10-13 14:38
I'm not sure there's anything I can do to change the behavior of the desktop client.

As far as I can tell (from the web UI), all of the files are created with the proper filenames now, when used with Cryptomator.

**Comment by leowankerddd** [comment] 2024-10-14 00:29
> Regarding the MEGA desktop client, do you plan on fixing the issue or not? Just so i know should i migrate to another drive 

My gut is telling me that the mega Windows client for synchronization is going to be a continual problem.

I would set up an Rclone batch file on your PC that synchronizes the files between your local Vault and your Cloud vault.

The only copy of my active vault is on my cloud drive and I on a weekly basis back the cloud drive up to a local SSD.

I've been testing with pcloud and be cloud has a synchronization program also I will set that up and see if it makes a difference but unlike the mega Clan the pcloud client automatically Maps the drive letter P to your cloud account so you don't need any third party tools .

I purchased pea cloud last year on Black Friday. I signed up first for a free account and then I was offered the opportunity to purchase 2 TB of Lifetime storage with no more Annual fees for about $240. I thought that was a pretty decent deal for never having to pay another month of fees for online storage and they have a nice Windows client and as well as a very nice Linux client. And it works with rclone and most importantly it's built-in to the kryptameter client for Android.

**Comment by avineas** [comment] 2024-10-28 16:11
Hi @chenxiaolong, off-topic but i didn't want to create a new issue to ask this: why does "crypt" wrapper remote seem to work even without granting RSAF storage permissions, i set up a crypt inside MEGA remote and it works fine?

**Comment by chenxiaolong** [comment] 2024-10-28 16:57
Storage permissions are never needed unless you have a remote that accesses the local filesystem (eg. `/sdcard`).

**Comment by avineas** [comment] 2024-10-28 17:46
Yeah that makes sense 😅. 
Btw the only advantage roundsync still has that i'm aware of is that there was a [PR](https://github.com/seedvault-app/seedvault/pull/609) for seedvault that made Roundsync and its remotes a viable target for seedvault backups. Idk how hard would this be to implement and if it would be worth your time, just mentioning it.

**Comment by chenxiaolong** [comment] 2024-10-28 19:56
That's...interesting. I don't think I've ever seen an app manually whitelist document providers like that before. I currently don't plan on making a PR myself since I don't have any way to test it (I'm using a different backup provider that conflicts with Seedvault).
